add_newline = true

[line_break]
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[package]
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = 'user: [$user]($style) '
disabled = true
show_always = true



[lua]
format = "via [🌕 $version](bold blue) "

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
